In [17]:
import numpy as np
from scipy import linalg as la
import sympy
A = np.array([[12,1, 3], [41,3, 5]])
B=np.array([[2,1],[3,4], [41,5]])

In [21]:
C=np.matmul(A,B)

In [22]:
evals,evecs=la.eig(C)

In [23]:
evals

array([ 216.33279044+0.j,   11.66720956+0.j])

In [24]:
evecs

array([[ 0.4233867 , -0.21867367],
       [ 0.90594906,  0.97579805]])

In [27]:
#we use la.eigh and la.eigvalsh, giving a real-valued eigenvalue arrays

In [28]:
evalsh,evecsh=la.eigh(C)

In [29]:
evalsh

array([-184.18115299,  412.18115299])

In [30]:
evecsh

array([[ 0.66304903, -0.74857597],
       [-0.74857597, -0.66304903]])

In [31]:
#Diagonalize Matrix

In [35]:
import numpy as np
a = np.matrix([[12,1, 3], [41,3, 5]])

In [36]:
a

matrix([[12,  1,  3],
        [41,  3,  5]])

In [37]:
d = np.diag(a)
print (d)

[12  3]


In [40]:
#Make 3 dim array (3X4X2) (width, height, depth) by using numpy. Get sum of numbers at depth = 0 and depth =1
import numpy as np
arr=np.arange(0,24,1).reshape(3,4,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [41]:
sum_depth0=np.sum(arr[:,:,0:1],axis=2)

In [42]:
sum_depth0

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
sum_depth1=np.sum(arr[:,:,1:2],axis=2)

In [44]:
sum_depth1

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [49]:
# Find the sum of first 100 odd numbers by using numpy
A=np.arange(1,200,2)

In [50]:
A

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199])

In [51]:
sum_odd=np.sum(A)

In [52]:
sum_odd

10000